version: '3.8'
services:
  db:
    image: mysql:8.0
    container_name: expressjs01-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: expressjs01_db
      MYSQL_USER: express_user
      MYSQL_PASSWORD: express_pass
    ports:
      - "55000:3306" # host:container -> host 3308 maps to container 3306
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
